site_name: OpenSAFELY documentation
nav:
    - Introduction: index.md
    - How OpenSAFELY works:
        - Our philosophy: open-methods.md
        - Not just another TRE: coming-soon.md
        - Security: workflow-security-levels.md
    - Data sources:
        - Overview: dataset-intro.md
        - Primary care records: dataset-systmone.md
        - Covid-19 test results: dataset-sgsscovid.md
        - Emergency attendances: dataset-ecds.md
        - Hospital admissions:  dataset-apc.md
        - Intensive care admissions (covid-19 only): dataset-icnarc.md
        - In-hospital deaths (covid-19 only): dataset-cpns.md
        - Registered deaths: dataset-onsdeaths.md
    - Installation:
        - Overview: install-intro.md
        - GitHub and Git: install-github-and-git.md
        - Python: install-python.md
        - Docker: install-docker.md
    - cohortextractor: cohortextractor.md
    - Research workflows:
        - Workflow: workflow.md
        - Create a repository: workflow-make-repo.md
        - Write a Study Definition: workflow-write-study-def.md
        - Generate the dummy data: workflow-make-dummy-data.md
        - Develop analysis scripts: workflow-develop-analysis-scripts.md
        - Test the code: workflow-testing-the-code.md
        - Execute the analysis on the real data: workflow-job-runner.md
        - Check the output for disclosivity: workflow-check-disclosivity.md
        - Project folder structure: workflow-folder-structure.md
    - Study definitions: study-def.md
    - Study definition variable reference: study-def-variables.md
    - Inclusion/exclusion flow charts: study-def-flowcharts.md
    - Measures: measures.md
    - Codelists:
        - Introduction to codelists: codelist-intro.md
        - Building a codelist: codelist-creation.md
        - Adding codelists to Project: codelist-project.md
        - SNOMED codelists: codelist-snomed.md
    - Running and testing code: pipelines.md
    - Good Practice:
        - Good practice: good-practice-intro.md
        - The Datalab Open Manifesto: open-data-manifesto.md
        - Developing a protocol: protocol.md
        - Using Git effectively: git-workflow.md
        - Code reviews: code-reviews.md
    - Feature requests and bug reports:
        - Overview: requests-intro.md
        - Adding packages: requests-packages.md
        - Adding Study Definition variables: requests-variables.md
        - Updating the Documentation: requests-documentation.md
    - Code of conduct: code-of-conduct.md

theme: material

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            rendering:
                show_root_heading: true
                show_root_toc_entry: false
                show_root_full_path: false
                show_source: false
                show_if_no_docstring: true
                heading_level: 4

markdown_extensions:
    - pymdownx.snippets:
        check_paths: true
    - toc:
        permalink: "&#128279;"
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition
    - footnotes
    - abbr
