site_name: OpenSAFELY documentation
nav:
    - Introduction: index.md
    - How OpenSAFELY works:
        - Our philosophy: open-methods.md
        - Not just another TRE: coming-soon.md
        - Security: security-levels.md
        - Analysis workflow: workflow.md
    - Data sources:
        - Overview: dataset-intro.md
        - Primary care records: dataset-systmone.md
        - Covid-19 test results: dataset-sgsscovid.md
        - Emergency attendances: dataset-ecds.md
        - Hospital admissions:  dataset-apc.md
        - Intensive care admissions (covid-19 only): dataset-icnarc.md
        - In-hospital deaths (covid-19 only): dataset-cpns.md
        - Registered deaths: dataset-onsdeaths.md
    - Installation:
        - Overview: install-intro.md
        - GitHub and Git: install-github-and-git.md
        - Python: install-python.md
        - Docker: install-docker.md
        - OpenSAFELY CLI: opensafely-cli.md
        - macOS: install-macos.md
    - Project repositories: repositories.md
    - Study definitions: study-def.md
    - Study definition variable reference: study-def-variables.md
    - cohortextractor: cohortextractor.md
    - Inclusion/exclusion flow charts: study-def-flowcharts.md
    - Measures: measures.md
    - Codelists:
        - Introduction to codelists: codelist-intro.md
        - Building a codelist: codelist-creation.md
        - Adding codelists to Project: codelist-project.md
        - SNOMED codelists: codelist-snomed.md
    - Running and testing code: pipelines.md
    - Releasing files from the server: releasing-files.md
    - Good Practice:
        - Good practice: good-practice-intro.md
        - The Datalab Open Manifesto: open-data-manifesto.md
        - Developing a protocol: protocol.md
        - Using Git effectively: git-workflow.md
        - Code reviews: code-reviews.md
    - Feature requests, bug reports:
        - Overview: requests-intro.md
        - Adding packages: requests-packages.md
        - Adding Study Definition variables: requests-variables.md
        - Updating the Documentation: requests-documentation.md

theme: material

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            rendering:
                show_root_heading: true
                show_root_toc_entry: false
                show_root_full_path: false
                show_source: false
                show_if_no_docstring: true
                heading_level: 4
        custom_templates: templates

markdown_extensions:
    - pymdownx.snippets:
        check_paths: true
    - toc:
        permalink: "&#128279;"
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition
    - footnotes
    - abbr
    - md_in_html
