site_name: OpenSAFELY documentation
nav:
    - Introduction: index.md
    - Updating the Documentation: updating-documentation.md
    
    - Our Philosophy:
        - Open Working Methods: open-methods.md
        - The Datalab Open Manifesto: open-data-manifesto.md
    - Data sources: dataset-landing-page.md
    - Getting started:
        - Overview: getting-started.md
        - GitHub and Git: install-github-and-git.md
        - Python: install-python.md
        - Docker: install-docker.md
    - cohortextractor: cohortextractor.md
    - Platform overview:
        - Workflow: workflow.md
        - Create a repository: workflow-make-repo.md
        - Write a Study Definition: workflow-write-study-def.md
        - Generate the dummy data: workflow-make-dummy-data.md
        - Develop analysis scripts: workflow-develop-analysis-scripts.md
        - Write a project pipeline: workflow-write-project-pipeline.md
        - Test the code: workflow-testing-the-code.md
        - Execute the analysis on the real data: workflow-job-runner.md
        - Check the output for disclosivity: workflow-check-disclosivity.md
        - Project Folder Structure: workflow-folder-structure.md
        - Glossary: glossary.md
    - Study definitions:
        - Introduction: study-def-intro.md
        - Basic structure: study-def-structure.md
        - Codelists: study-def-codelists.md
        - Defining Time Periods: study-def-time.md
        - Defining dummy data: study-def-dummy-data.md
        - Defining a Precise Study Population: study-def-population.md
        - Multiple Study Definitions: study-def-multiple-populations.md
        - Study Flow Charts: study-def-flowcharts.md
        - Variable extractor functions: study-def-extractor-functions.md
    - Measures: measures.md
    - Codelists:
        - Introduction to Codelists: codelist-intro.md
        - Building a Codelist: codelist_creation.md
        - Adding Codelists to Project: codelist_project.md
        - SNOMED codelists: snomed.md
    - Project pipelines: project-pipelines.md
    - Good Practice:
        - Good practice: good-practice-intro.md
        - Developing a Protocol: protocol.md
        - Using Git Effectively: git-workflow.md
        - Code Reviews: code-reviews.md
    - First-time walkthrough: onboarding_analysts.md
    - Code of conduct: code-of-conduct.md


theme: material
plugins:
    - search
    - mkdocstrings:
        docstring_options:
            show_source: False

markdown_extensions:
    - toc:
        permalink: "&#128279;"
    - pymdownx.highlight
    - pymdownx.superfences