site_name: OpenSAFELY documentation
nav:
    - Home: index.md
    - Updating the Documentation: updating_documentation.md
    - Our Philosophy:
        - Open Working Methods: our_philosophy.md
        - The Datalab Open Manifesto: open_data_manifesto.md
    - Overview:
        - Workflow Overview: overview_pipeline.md
        - Minimal Requirements: min_req.md
        - Datasets: dataset_landing_page.md
    - Setting up your Project:
        - Developing a Research Question and Protocol: protocol.md
        - Creating your Project Repo on Github: project_setup.md
    - Codelists:
        - Introduction to Codelists: codelist_intro.md
        - Building a Codelist: codelist_creation.md
    - Getting started checklist: getting_started_checklist.md
    - First-time walkthrough: onboarding_analysts.md
    - Study definitions:
        - Study definition walkthrough: study_definition.md
        - Full API: study_definition_api.md
    - Project pipelines: project_pipelines.md
    - Codelists:
        - Creating codelists: codelist_creation.md
        - SNOMED codelists: snomed.md
    - Installing Docker: installing_docker.md

theme: material
plugins:
    - search
    - mkdocstrings:
        docstring_options:
            show_source: False
