site_name: OpenSAFELY documentation
repo_url: https://github.com/opensafely/documentation
nav:
  - Introduction: index.md
  - How OpenSAFELY works:
      - Our philosophy: open-methods.md
      - Security: security-levels.md
      - Analysis workflow: workflow.md
  - Getting Started guide: getting-started.md

  - How-to guides:
      - Inclusion/exclusion flow charts: study-def-flowcharts.md
      - Releasing files from the server: releasing-files.md
  - Reference:
      - Detailed installation guides:
          - Overview: install-intro.md
          - GitHub and Git: install-github-and-git.md
          - Python: install-python.md
          - Docker: install-docker.md
          - OpenSAFELY CLI: opensafely-cli.md
          - macOS: install-macos.md
      - Github repository layout: repositories.md
      - Study definitions:
          - Overview: study-def.md
          - Working with dates: study-def-dates.md
          - Working with codelists: study-def-codelists.md
          - Dummy data and expectations: study-def-expectations.md
          - Variable reference: study-def-variables.md
          - Measures: measures.md
      - Codelists:
          - Introduction to codelists: codelist-intro.md
          - Building a codelist: codelist-creation.md
          - Adding codelists to Project: codelist-project.md
          - SNOMED codelists: codelist-snomed.md
      - Actions:
          - Overview: actions-intro.md
          - Scripted actions: actions-scripts.md
          - The `cohortextractor` action: actions-cohortextractor.md
          - The project pipeline: actions-pipelines.md
      - Job server: job-server.md
      - Data sources:
          - Overview: dataset-intro.md
          - Systmone primary care: dataset-systmone.md
          - EMIS primary care: dataset-emis.md
          - Externally linked data:
              - Covid-19 test results: dataset-sgsscovid.md
              - Emergency attendances: dataset-ecds.md
              - Hospital admissions: dataset-apc.md
              - Intensive care admissions (covid-19 only): dataset-icnarc.md
              - In-hospital deaths (covid-19 only): dataset-cpns.md
              - Registered deaths: dataset-onsdeaths.md
  - Good Practice:
      - Good practice: good-practice-intro.md
      - The Datalab Open Manifesto: open-data-manifesto.md
      - Developing a protocol: protocol.md
      - Using Git effectively: git-workflow.md
      - Code reviews: code-reviews.md
  - Updating the Documentation: requests-documentation.md
  - Support:
      - Overview: requests-intro.md
      - Requesting new libraries: requests-packages.md
      - Requesting Study Definition variables: requests-variables.md

theme:
  name: material
  custom_dir: overrides

extra_css:
  - css/youtube.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            show_source: false
            show_if_no_docstring: true
            heading_level: 4
      custom_templates: templates

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: "&#128279;"
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - admonition
  - footnotes
  - abbr
  - md_in_html
